name: Build

on: [push, pull_request]

jobs:
  build-binary:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build binary
      run: |
        docker build -t flamecafe_builder .
        docker run --rm -v ${PWD}:/project flamecafe_builder make
    - uses: actions/upload-artifact@master
      with:
       name: FlameCafe
       path: "*.wps"
       if-no-files-found: error
